### ISSUE TITLE
Taunt not working

### ISSUE THREAD

**Issue by Tilier** [tylermurphy534/KenshinsHideAndSeek#18]
**Describe the bug**
When it says the taunt should happen, nothing happens.

**To Reproduce**
1. Have one hider and one seeker (I'm not sure if this is only with one hider or not)
2. Enable taunts for last person
3. Wait for taunt to happen

**Expected behavior**
A firework should be spawned, and the person should be notified that they will be taunted

**Screenshots**
None needed

**System Info (please complete the following information):**
 - MacOS
 - Minefort
 - 1.17.1
 - 1.3.2

**Additional context**
Nothing else.

**Comment by tylermurphy534** [comment]
Hello, currently in 1.3.3 development, I rewrote the entire taunt/glow/worldbrder systems so that they are more optimized. Can you try downloading 1.3.3 rc1 from the repos actions panel and see if that fixes it? Thanks!

**Comment by tylermurphy534** [comment]
And if there are any errors, please send the stack trace from the console. That's the big blob of text that appears when something errors.

**Comment by Tilier** [comment]
Okay, thanks!! I'll try it when I have a friend available to play with me.

**Comment by tylermurphy534** [comment]
I just tested it myself with my main and one of my alt accounts and it seems to work. Its possible It was fixed when I rewrote the taunting system. If this issue still stands on your end, please send the stack trace, otherwise I'll close this issue and release update 1.3.3.

**Comment by Tilier** [comment]
Okay! Sorry, still trying to get a friend to play with me loll

**Comment by tylermurphy534** [comment]
If you want, I can hop on your server and test it w/ you.

**Comment by Tilier** [comment]
Huh . . . the taunt didn't work. Also, my friend is stuck and can't move.

**Comment by Tilier** [comment]
Also bows don't work, but that's a different thing.

**Comment by tylermurphy534** [comment]
Can you send me the stack trace in the logs?

**Comment by tylermurphy534** [comment]
It would look something like this
```
Exception in thread "main" java.lang.NullPointerException
        at com.example.myproject.Book.getTitle(Book.java:16)
        at com.example.myproject.Author.getBookTitles(Author.java:25)
        at com.example.myproject.Bootstrap.main(Bootstrap.java:14)
```

**Comment by Tilier** [comment]
Okay, I will in a minute.

**Comment by Tilier** [comment]
No error . . . also, my friend was glitched and couldn't move until I opped her.

**Comment by tylermurphy534** [comment]
Ok so i found out the not being able to move thing. My bounding box collision checking for the bounds was incorrect. I will push that to the github in a moment. But you said that no firework launched still, yet no errors in the log?

**Comment by Tilier** [comment]
Yeah

**Comment by tylermurphy534** [comment]
Are you using 1.3.3 rc1 or 1.3.3 rc2 currently. As I added some changes to the taunt code in rc2 to possible fix your issue.

**Comment by Tilier** [comment]
rc1, i'll install rc2

**Comment by tylermurphy534** [comment]
Install rc3 as I just pushed it to fix the teleport issue.

**Comment by Tilier** [comment]
Okay!! All's working, thank you so much!

(Also, unrelated, how do you get bows to work)

**Comment by tylermurphy534** [comment]
you would have to give them a bow and some arrows (obliviously).

To do this, i would look at the wiki page for the repo. 

To give a bow, the material field should be `material: BOW` exactly. And for standard arrows, 'material: ARROW'. Make sure that the items are in numericial order in the '1': '2': '3': numbering. If it skips a number, It will stop reading the file there.

**Comment by tylermurphy534** [comment]
the list of materials you can use are listed here
[https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)

**Comment by Tilier** [comment]
No I got the giving the bow, but it doesn't give any damage.
Also, I found some other glitches:
- someone died and was teleporting back to the main world, not the spawn
- I was killed as a hider and I think a taunt spawned on me as a then-hunter . . .

**Comment by tylermurphy534** [comment]
Interesting, ill look into that rn. I shoudnt be canceling arrow projectile events, but ill still look

**Comment by tylermurphy534** [comment]
shit i guess I am, well then. Time to get back to work

**Comment by tylermurphy534** [comment]
pushed rc4

**Comment by tylermurphy534** [comment]
If there is no further response I will have to close this issue. If you still have any bugs, please tell me here.

**Comment by Tilier** [comment]
Okay! If you fixed all this, then that's it! Thanks so much for your help.

> No I got the giving the bow, but it doesn't give any damage. Also, I found some other glitches:
> 
> * someone died and was teleporting back to the main world, not the spawn
> * I was killed as a hider and I think a taunt spawned on me as a then-hunter . . .
