### ISSUE TITLE
Feature request: Placeholders for statistics

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#26]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
I'd love to use placeholders to display the /hs top, and /hs wins stuff in holograms.

Example:
/hs top
%hs_top_<place>%

/hs wins
%hs_stats_total-wins% - displays the person who views the hologram's stats-
%hs_stats_hider-wins%
%hs_stats_seeker-wins%
%hs_stats_games-played%

**/hs wins should also display kills as hider and seeker.**
%hs_stats_kills-as-hider%
%hs_stats_kills-as-seeker%

**Other placeholders could be**
%hs_total-games% - total games played on the server.
%hs_total-hider-wins% - total games won by hiders.
%hs_total-seeker-wins% - total games won by seekers.
%hs_total-kills-by-seeker% - total kills seekers have gotten.
%hs_total-kills-by-hider% - total kills hiders have gotten.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Nesseley** [comment]
It also seems to be that there is no saving of statistics. I've played bunch of test games now and my stats is still 0

**Comment by tylermurphy534** [comment]
Have you actually won these games? The stats currently only track wins, and if you have no wins, it displays as 0. 

If you have run these commands, can you check your server logs, and send any errors from the plugin. Its possible the plugin doesn't have file access to the database.

**Comment by Nesseley** [comment]
I'm pretty sure I've won and lost multiple games. It's just me and my test-account in the game. So I've killed myself many times.

I do get an error:
[22:15:17 INFO]: Nesseley issued server command: /hs wins
[22:15:17 ERROR]: [HideAndSeek] SQL Error: ResultSet closed

**Comment by tylermurphy534** [comment]
Can i have the full error, or is that all that shows up?

**Comment by tylermurphy534** [comment]
I just pushed another build that prints the entire stack trace when an error occurs. Can you download that and send what it puts in the console? Thanks.

**Comment by Nesseley** [comment]
That was everything yeah. Here with the new build:
```
[22:38:34 INFO]: Nesseley issued server command: /hs wins
[22:38:34 ERROR]: [HideAndSeek] SQL Error: ResultSet closed
[22:38:34 WARN]: java.sql.SQLException: ResultSet closed
[22:38:34 WARN]:        at org.sqlite.core.CoreResultSet.checkOpen(CoreResultSet.java:76)
[22:38:34 WARN]:        at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:39)
[22:38:34 WARN]:        at org.sqlite.jdbc3.JDBC3ResultSet.getInt(JDBC3ResultSet.java:402)
[22:38:34 WARN]:        at HideAndSeek-1.4.3.jar//net.tylermurphy.hideAndSeek.database.PlayerInfoTable.getInfo(PlayerInfoTable.java:69)
[22:38:34 WARN]:        at HideAndSeek-1.4.3.jar//net.tylermurphy.hideAndSeek.command.Wins.lambda$execute$0(Wins.java:60)
[22:38:34 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[22:38:34 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:38:34 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:38:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:38:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:38:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by tylermurphy534** [comment]
Pushed a new build, see if that works :)

**Comment by Nesseley** [comment]
I shall disappoint with a no :P 

```
[22:50:49 INFO]: Nesseley issued server command: /hs wins
[22:50:49 ERROR]: [HideAndSeek] SQL Error: The prepared statement has been finalized
[22:50:49 WARN]: java.sql.SQLException: The prepared statement has been finalized
[22:50:49 WARN]:        at org.sqlite.core.NativeDB.throwex(NativeDB.java:510)
[22:50:49 WARN]:        at org.sqlite.core.NativeDB.column_int(Native Method)
[22:50:49 WARN]:        at org.sqlite.jdbc3.JDBC3ResultSet.getInt(JDBC3ResultSet.java:395)
[22:50:49 WARN]:        at org.sqlite.jdbc3.JDBC3ResultSet.getInt(JDBC3ResultSet.java:402)
[22:50:49 WARN]:        at HideAndSeek-1.4.3.jar//net.tylermurphy.hideAndSeek.database.PlayerInfoTable.getInfo(PlayerInfoTable.java:68)
[22:50:49 WARN]:        at HideAndSeek-1.4.3.jar//net.tylermurphy.hideAndSeek.command.Wins.lambda$execute$0(Wins.java:60)
[22:50:49 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[22:50:49 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:50:49 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:50:49 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:50:49 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:50:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by tylermurphy534** [comment]
new build! lol

**Comment by Nesseley** [comment]
`/hs wins` seems to be fixed and updating right! 👍 

I will let this be open as it was originally for placeholders :)

**Comment by tylermurphy534** [comment]
Currently PlaceholderAPIs eCloud is currently not accepting registrations. So I will be unable to upload the placeholders until that changes. Stay tuned though!

**Comment by tylermurphy534** [comment]
Uploaded new build today that adds PlaceholderAPI support. You can use it on HolographicDisplays 3, or HolographicDisplays 2 with HolographicExtension if you run 1.15 or prior.

You must have ProtocolLib and PlaceholderAPI installed for this to work :)

Currently deaths and kills are counted on the team you are on, no matter what team you started as. So if you start a hider, then get found, then die as a seeker, your seeker deaths goes up. Would you want this to only go up for your original team, or keep it how it is?

Finally, the database was rewritten, to database will be reset. Old data won't be deleted though, I just store stuff in a separate SQL table, At some point ill make it so the plugin copy's stuff over automatically.

***The placeholders I added:***
%hs_stats\_\<stat-name>%
%hs_stats\_\<stat-name>\_\<player-name>%
%hs_rank-score\_\<stat-name>\_\<place>%
%hs_rank-name\_\<stat-name>\_\<place>%

***Stat Names:***
total-wins
hider-wins
seeker-wins
total-games
hider-games
seeker-games
total-kills
hider-kills
seeker-kills
total-deaths
hider-deaths
seeker-deaths

**Comment by Nesseley** [comment]
Currently deaths and kills are counted on the team you are on, no matter what team you started as. So if you start a hider, then get found, then die as a seeker, your seeker deaths goes up. Would you want this to only go up for your original team, or keep it how it is?

You should only get stats on the team you are currently on. Get a kill as a hider = +1 on the kills as hider, if you then die and get kills as a seeker the +1 should go to the kills as seeker.

i am not able to test the placeholders fully because of the end error I posted in [the other comment](https://github.com/tylermurphy534/KenshinsHideAndSeek/issues/40) :)

**Comment by tylermurphy534** [comment]
Yes that is how it works, rank-score displays the score number, and rank-name displays the name. This allows you to customize how you want your leader-board to be styled.

Added %hs_rank-place\_\<stat-name>\_\<player-name>% and %hs_rank-place\_\<stat-name>%

**Comment by Nesseley** [comment]
This placeholder seems a bit weird: `%hs_stats_seeker-deaths%` 

I don't have PVP enabled, so in theory the seeker can't die. But the number goes up when I'm playing games.
I was just killed as a hider and `%hs_stats_hider-deaths%` did not change, but seeker-deaths did, so it might register on the wrong stats.

**Comment by Nesseley** [comment]
`%hs_rank-place_<stat-name>_<player-name>%` What do I replace <player-name> with here? I want it to change based on the player that looks at it. :)

**Comment by Nesseley** [comment]
Error would be `%hs_rank-place_total-wins_<player-name>%` I just don't know what to replace <player-name> with x)

> That's the same thing of the other rank-place placeholder, it just allows you to only show the rank of a certain player instead of the player looking at it
I don't quite understand what you mean. My screen shot shows that it's showing the wrong placement for me

**Comment by tylermurphy534** [comment]
%hs_rank-place_total-wins% shows the current ranking of total-wins for the current player looking at it

%hs_rank-place_total-wins_KenshinEto% shows the current ranking of total-wins for KenshinEto.

**Comment by Nesseley** [comment]
`%hs_rank-place_total-wins%` is bugged then.

Nesseley has won total of 0, hider 0, seeker 0. 
But it still shows as 1 on all the three placeholders below. (And there is other users with wins, so Nesseley can't be number `1` on the placements) Users with no data saved should just see a `-`
![image](https://user-images.githubusercontent.com/11998470/167706178-ebbd70d5-833e-479b-8d9b-7f02d239d902.png)


Sjokoladeku has a total win of 2 and is in first place, but it shows `3` `1` `3`on the above placeholders. Even though it should be `1` `-` `1`
![image](https://user-images.githubusercontent.com/11998470/167706364-c5078475-803f-4078-876e-2bc8543e0386.png)

**Comment by tylermurphy534** [comment]
Uploaded a new build, try it now

**Comment by Nesseley** [comment]
There's still an issue where by friend Bluebear96 sees her placement as 1, even though it should be 2.

She sees `1` `-` `1` but it should be `2` `-` `2` as you can see in the screenshot below, taken from the view as Bluebear96.  
![image](https://user-images.githubusercontent.com/11998470/167812154-3566d6e4-582b-4e3a-a5ca-af69fde6c6fb.png)



> This placeholder seems a bit weird: `%hs_stats_seeker-deaths%`
> 
> I don't have PVP enabled, so in theory the seeker can't die. But the number goes up when I'm playing games. I was just killed as a hider and `%hs_stats_hider-deaths%` did not change, but seeker-deaths did, so it might register on the wrong stats.

This is still an issue.

**Comment by tylermurphy534** [comment]
uploaded new build!

**Comment by Nesseley** [comment]
Yey, it's fixed! :D 

I really appreciate your work on this plugin! :D
