### ISSUE TITLE
Bug Report: Seeker can't tag Hider

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#40]
**Describe the bug**
My build: https://github.com/tylermurphy534/KenshinsHideAndSeek/actions/runs/2282868416
Seekers can't kill the hiders on this build with pvp: false setting

**To Reproduce**
-

**Expected behavior**
-

**Screenshots**
-

**System Info (please complete the following information):**
-

**Additional context**
-

**Comment by tylermurphy534** [comment]
just uploaded a new build that completely rewrote the EntityDamageEvent thing. See if it works for you now

**Comment by Nesseley** [comment]
I can kill now, but it doesn't exit the players back to the hub. Error:
```
[10:58:21 WARN]: [HideAndSeek] Task #2574 for HideAndSeek v1.4.3 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
        at net.tylermurphy.hideAndSeek.database.PlayerInfoTable.addWins(PlayerInfoTable.java:200) ~[HideAndSeek-1.4.3.jar:?]
        at net.tylermurphy.hideAndSeek.game.Game.stop(Game.java:185) ~[HideAndSeek-1.4.3.jar:?]
        at net.tylermurphy.hideAndSeek.game.Game.lambda$end$1(Game.java:168) ~[HideAndSeek-1.4.3.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-267]        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-267]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by tylermurphy534** [comment]
uploaded new build, it was do to a null pointer in the sql query. Fixed now

**Comment by Nesseley** [comment]
Fixed :)
