### ISSUE TITLE
Failed to select random seeker ????

### ISSUE THREAD

**Issue by lovemercer** [tylermurphy534/KenshinsHideAndSeek#74]
**Describe the bug**

Set everything up, but the message Failed to select random seeker at the beginning

**To Reproduce**
1. Go to (https://github.com/tylermurphy534/KenshinsHideAndSeek/wiki/2)-Setup)
2. Follow the steps to set the parameters
3. Two players, using quick start
4. See error :  [15:48:35 WARN]: [KenshinsHideAndSeek] Failed to select random seeker.

**Expected behavior**
The execution command will occur: /hs setup
Hide and Seek >Everything is setup and ready to go!

The execution command will occur:  /hs start XXX
[15:51:24 WARN]: net.minecraft.server.v1_8_R3.ReportedException: Exception generating new chunk
[15:51:24 WARN]:        at net.minecraft.server.v1_8_R3.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:167)
[15:51:24 WARN]:        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:135)
[15:51:24 WARN]:        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:114)
[15:51:24 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.createWorld(CraftServer.java:931)
[15:51:24 WARN]:        at net.tylermurphy.hideAndSeek.world.WorldLoader.loadMap(WorldLoader.java:68)
[15:51:24 WARN]:        at net.tylermurphy.hideAndSeek.world.WorldLoader.rollback(WorldLoader.java:79)
[15:51:24 WARN]:        at net.tylermurphy.hideAndSeek.game.Game.start(Game.java:121)
[15:51:24 WARN]:        at net.tylermurphy.hideAndSeek.command.Start.execute(Start.java:74)
[15:51:24 WARN]:        at net.tylermurphy.hideAndSeek.util.CommandHandler.handleCommand(CommandHandler.java:87)
[15:51:24 WARN]:        at net.tylermurphy.hideAndSeek.Main.onCommand(Main.java:130)
[15:51:24 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:51:24 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:51:24 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640)
[15:51:24 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1165)
[15:51:24 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000)
[15:51:24 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:51:24 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:51:24 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[15:51:24 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:51:24 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:51:24 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[15:51:24 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:771)
[15:51:24 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[15:51:24 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710)
[15:51:24 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613)
[15:51:24 WARN]:        at java.lang.Thread.run(Thread.java:750)
[15:51:24 WARN]: Caused by: java.lang.UnsupportedOperationException: Custom generator is missing required methods: generate(), generateBlockSections() and generateExtBlockSections()
[15:51:24 WARN]:        at org.bukkit.generator.ChunkGenerator.generate(ChunkGenerator.java:76)
[15:51:24 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:99)
[15:51:24 WARN]:        at net.minecraft.server.v1_8_R3.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:159)
[15:51:24 WARN]:        ... 25 more

**Screenshots**
![error1](https://user-images.githubusercontent.com/54006090/184827662-9378bdee-452c-47dd-b9d8-e541e6ad6451.png)
![error2](https://user-images.githubusercontent.com/54006090/184827687-cc63388d-e99b-412e-b117-fcf8dd8a23f2.png)
![error3](https://user-images.githubusercontent.com/54006090/184827709-5e10b3cf-4859-436d-a204-c247b9898f5a.png)

**System Info (please complete the following information):**
 - OS: CenOS 8
 - Server Host [e.g. Apex/Custom]
 - MC Version PaperSpigot 1.8.8
 - Plugin Version 1.16.0

**Comment by tylermurphy534** [comment]
Just uploaded a new 1.6.1 beta build that should fix this.

**Comment by lovemercer** [comment]
It now STARTS CORRECTLY, BUT AN ERROR IS reported WHEN THE HIDING IS caught, causing the player not exit playergame
![error4](https://user-images.githubusercontent.com/54006090/185148423-0df545f0-a1ba-4e37-a1f5-db4aee2e06e8.png)

**Comment by tylermurphy534** [comment]
that Error is not related, though that error is now fixed in 1.6.2 beta. Can you try that and then send me your logs, thanks

**Comment by LowLie4** [comment]
I have the same problem with version 1.19.2

**Comment by tylermurphy534** [comment]
Interesting, I will have to look into this again. Again im not sure why this is happening as its hard for me to reproduce.

**Comment by LowLie4** [comment]
When you have many info for the solution, tell me, ty

**Comment by tylermurphy534** [comment]
Repo moved
https://git.tylermurphy.net/tylermurphy534/KenshinsHideAndSeek/issues

(I am still working on this dont worry)
