### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by TechnicalityMods** [tylermurphy534/KenshinsHideAndSeek#84]
When I added the plugin, It says:
04.10 00:24:21 [Server] INFO [KenshinsHideAndSeek] Enabling KenshinsHideAndSeek v1.6.2
04.10 00:24:21 [Server] ERROR Error occurred while enabling KenshinsHideAndSeek v1.6.2 (Is it up to date?)
04.10 00:24:21 [Server] INFO java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener
04.10 00:24:21 [Server] INFO at net.tylermurphy.hideAndSeek.Main.onEnable(Main.java:70) ~[KenshinsHideAndSeek-1.6.2.jar:?]
04.10 00:24:21 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
04.10 00:24:21 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
04.10 00:24:21 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
04.10 00:24:21 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-173]
04.10 00:24:21 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-173]
04.10 00:24:21 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.2.jar:git-Paper-173]
04.10 00:24:21 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-173]
04.10 00:24:21 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-173]
04.10 00:24:21 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
04.10 00:24:21 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketListener
04.10 00:24:21 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:172) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
04.10 00:24:21 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
04.10 00:24:21 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
04.10 00:24:21 [Server] INFO ... 10 more
04.10 00:24:21 [Server] INFO [KenshinsHideAndSeek] Disabling KenshinsHideAndSeek v1.6.2

**To Reproduce**
1. Load the plugin into the server (Along with ProtocolLib)
2. Start the server (Version 1.19.2)
3. See error

**Expected behavior**
I expected it to load properly and let me use the plugin

**Screenshots**
![image](https://user-images.githubusercontent.com/91298884/193709000-3c552538-7f23-46c2-9d22-85dfda3f7dd6.png)

**System Info (please complete the following information):**
 - OS: I use windows, the server, IDK
 - Server Host Apex Hosting
 - MC Version 1.19.2
 - Plugin Version 1.6.2

**Additional context**

**Comment by TechnicalityMods** [comment]
It gives a new error code
04.10 00:39:28 [Server] ERROR Could not load 'plugins/KenshinsHideAndSeek-1.6.2.jar' in folder 'plugins'
04.10 00:39:28 [Server] INFO org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [ProtocolLib]. Please download and install these plugins to run 'KenshinsHideAndSeek'.
04.10 00:39:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:287) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
04.10 00:39:28 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.2.jar:git-Paper-173]
04.10 00:39:28 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.2.jar:git-Paper-173]
04.10 00:39:28 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-173]
04.10 00:39:28 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-173]
04.10 00:39:28 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by KaptenZee** [comment]
Yeah...i get same error..using latest protocolib

[11:24:17 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'hs' in plugin KenshinsHideAndSeek v1.6.2 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:947) ~[purpur-1.19.2.jar:git-Purpur-1800]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.2.jar:git-Purpur-1800]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2385) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2339) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1800]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1800]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1800]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1800]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1800]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1800]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1800]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1800]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by tylermurphy534** [comment]
@TechnicalityMods please make sure you are using the latest version of protocol lib. 

![image](https://user-images.githubusercontent.com/28487599/193889271-4aeefcbc-3640-48f2-b202-eae0cf66cbfc.png)

**Comment by TechnicalityMods** [comment]
I found this in the startup logs. would this lead to a problem? (Thanks for all the help so far!)

04.10 19:09:12 [Server] WARN [ProtocolLib] [PacketFilterManager] Plugin KenshinsHideAndSeek tried to register listener for unknown packet SPAWN_ENTITY_PAINTING[PLAY, SERVER, 243, classNames: [net.minecraft.network.protocol.game.PacketPlayOutSpawnEntityPainting, net.minecraft.network.protocol.game.ClientboundSpawnEntityPaintingPacket, net.minecraft.network.play.server.SPacketSpawnPainting] (unregistered)] [direction: from SERVER]
04.10 19:09:12 [Server] WARN [ProtocolLib] [PacketFilterManager] Plugin KenshinsHideAndSeek tried to register listener for unknown packet SPAWN_ENTITY_LIVING[PLAY, SERVER, 244, classNames: [net.minecraft.network.protocol.game.PacketPlayOutSpawnEntityLiving, net.minecraft.network.protocol.game.ClientboundSpawnEntityLivingPacket, net.minecraft.network.play.server.SPacketSpawnMob] (unregistered)] [direction: from SERVER]

**Comment by TechnicalityMods** [comment]
Nevermind! I fixed it by using the 2nd most recent dev build (#599) instead of the most recent (#600)

**Comment by tylermurphy534** [comment]
Im glad its working now! :3
