### ISSUE TITLE
Why this error in my console

### ISSUE THREAD

**Issue by KaptenZee** [tylermurphy534/KenshinsHideAndSeek#85]
[KenshinsHideAndSeek] Unhandled exception occurred in onPacketSending(PacketEvent) for KenshinsHideAndSeek
java.lang.UnsupportedOperationException: The method getEntityId is not supported for temporary players.
        at com.comphenix.protocol.injector.temporary.TemporaryPlayerFactory$1.delegate(TemporaryPlayerFactory.java:138) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler.getEntityId(Unknown Source) ~[ProtocolLib.jar:?]
        at net.tylermurphy.hideAndSeek.game.EntityHider.getMembership(EntityHider.java:107) ~[KenshinsHideAndSeek-1.6.2 (2).jar:?]
        at net.tylermurphy.hideAndSeek.game.EntityHider.isVisible(EntityHider.java:118) ~[KenshinsHideAndSeek-1.6.2 (2).jar:?]
        at net.tylermurphy.hideAndSeek.game.EntityHider$2.onPacketSending(EntityHider.java:181) ~[KenshinsHideAndSeek-1.6.2 (2).jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:570) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:473) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2257) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2243) ~[?:?]
        at net.minecraft.server.players.PlayerList.sendPlayerPermissionLevel(PlayerList.java:1201) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at net.minecraft.server.players.PlayerList.sendPlayerPermissionLevel(PlayerList.java:1185) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at net.minecraft.server.players.PlayerList.sendPlayerPermissionLevel(PlayerList.java:1030) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:287) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:222) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:203) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:91) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:577) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:233) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1594) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:56:53 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntityStatus@7ebb5a3b[
    a=290787
    b=24
  ]

**Comment by tylermurphy534** [comment]
Hello, when posting an issue, please follow the issue reporting format. Since errors can be different across Minecraft versions, Server software, and even operating systems, it is almost impossible to diagnose. So please comment with that information please!

**Comment by KaptenZee** [comment]
Sorry not very good in English..and im not technical person..new in server minecraft..but that error appear in my console. Im using 1.19.20 server.

**Comment by tylermurphy534** [comment]
Can you tell me what plugins you are using on your server?

**Comment by tylermurphy534** [comment]
Repo moved
https://git.tylermurphy.net/tylermurphy534/KenshinsHideAndSeek/issues
